#define IP_CONFIG_PATH "../config/ip.config"
#define CPU_CONFIG_PATH "../config/cpu.config"
#define KERNEL_CONFIG_PATH "../config/kernel.config"
#define MEMORIA_CONFIG_PATH "../config/memoria.config"
#define IO_CONFIG_PATH "../config/io.config"
